// GODZ Cafe & Restaurant menüsü — Excel'den çıkarılan tam üç dilli veri.
// prisma/seed.ts bu veriyi kullanarak Category/Product/Allergen kayıtlarını oluşturur.

export type MenuItem = {
  name: string;
  nameEn?: string;
  nameRu?: string;
  description?: string;
  descriptionEn?: string;
  descriptionRu?: string;
  price: number;
  calories?: number;
  allergenNames?: string[];
  image?: string;
};

export type MenuCategory = {
  name: string;
  nameEn?: string;
  nameRu?: string;
  section: "food" | "drink";
  image?: string;
  items: MenuItem[];
};

export const GODZ_MENU: MenuCategory[] = [
  {
    name: "Kahvaltı",
    nameEn: "Breakfast",
    nameRu: "Завтраки",
    section: "food",
    image: "/menu-seed-images/categories/breakfast.jpg",
    items: [
      {
        name: "Menemen",
        nameEn: "Menemen",
        nameRu: "Менемен",
        description: "Domates, biber, yumurta, soğan (isteğe bağlı), sarmısak (isteğe bağlı)",
        descriptionEn: "Tomatoes, peppers, eggs, onion (optional), garlic (optional)",
        descriptionRu: "Помидоры, перец, яйца, лук (по желанию), чеснок (по желанию)",
        price: 200,
        calories: 280,
        allergenNames: ["Yumurta"],
        image: "/menu-seed-images/items/menemen.jpg",
      },
      {
        name: "Sucuklu Yumurta",
        nameEn: "Eggs with Sucuk",
        nameRu: "Яичница с суджуком",
        description: "Yumurta, sucuk, tereyağı, yeşillik, ekmek",
        descriptionEn: "Eggs, Turkish sausage (sucuk), butter, herbs, bread",
        descriptionRu: "Яйца, суджук, сливочное масло, зелень, хлеб",
        price: 250,
        calories: 510,
        allergenNames: ["Yumurta"],
        image: "/menu-seed-images/items/eggs-with-sucuk.jpg",
      },
      {
        name: "Kaşarlı Tost",
        nameEn: "Cheese Toast",
        nameRu: "Тост с сыром",
        description: "Ekmek, peynir, patates kızartması, sos, domates",
        descriptionEn: "Bread, cheese, French fries, sauce, tomato",
        descriptionRu: "Хлеб, сыр, картофель фри, соус, помидор",
        price: 225,
        calories: 520,
        allergenNames: ["Gluten içeren tahıllar", "Süt (laktoz dahil)"],
        image: "/menu-seed-images/items/cheese-toast.jpg",
      },
      {
        name: "Karışık Tost",
        nameEn: "Mixed Toast",
        nameRu: "Тост ассорти",
        description: "Tost ekmeği, kaşar peyniri, sucuk, salam, domates, tereyağı, patates kızartması, ketçap, mayonez",
        descriptionEn: "Toast bread, cheese, sucuk, salami, tomato, butter, fries, ketchup, mayonnaise",
        descriptionRu: "Тостовый хлеб, сыр, суджук, салями, помидор, масло, картофель фри, кетчуп, майонез",
        price: 275,
        calories: 610,
        allergenNames: ["Gluten içeren tahıllar", "Süt (laktoz dahil)"],
        image: "/menu-seed-images/items/mixed-toast.jpg",
      },
      {
        name: "Akdeniz Tost",
        nameEn: "Mediterranean Toast",
        nameRu: "Средиземноморский тост",
        description: "Tost ekmeği, kaşar peyniri, beyaz peynir, zeytin ezmesi, domates, biber, roka, tereyağı, patates kızartması, ketçap, mayonez",
        descriptionEn: "Toast bread, cheese, white cheese, olive paste, tomato, pepper, arugula, butter, fries, ketchup, mayonnaise",
        descriptionRu: "Тостовый хлеб, сыр, белый сыр, оливковая паста, помидор, перец, руккола, масло, картофель фри, кетчуп, майонез",
        price: 295,
        calories: 580,
        allergenNames: ["Gluten içeren tahıllar", "Yumurta", "Süt (laktoz dahil)"],
        image: "/menu-seed-images/items/mediterranean-toast.jpg",
      },
      {
        name: "Sahanda Yumurta",
        nameEn: "Fried Eggs",
        nameRu: "Яичница",
        description: "3 yumurta, tereyağı",
        descriptionEn: "3 eggs, butter",
        descriptionRu: "3 яйца, сливочное масло",
        price: 200,
        calories: 340,
        allergenNames: ["Yumurta"],
        image: "/menu-seed-images/items/fried-eggs.jpg",
      },
      {
        name: "Somon ve Çırpılmış Yumurta ile Patates Mücveri",
        nameEn: "Potato Fritters with Salmon & Scrambled Egg",
        nameRu: "Картофельные оладьи с лососем и яйцом",
        description: "Patates mücveri, somon, çırpılmış yumurta, avokado ve ıspanak ile",
        descriptionEn: "Potato fritters, salmon, scrambled egg, avocado and spinach",
        descriptionRu: "Картофельные оладьи, лосось, яичница-болтунья, авокадо и шпинат",
        price: 350,
        calories: 740,
        allergenNames: ["Yumurta", "Süt (laktoz dahil)", "Balık"],
        image: "/menu-seed-images/items/potato-fritters-with-salmon-scrambled-egg.jpg",
      },
      {
        name: "Ricotta ve Karamelli Kremalı Syrniki",
        nameEn: "Ricotta Syrniki with Caramel Cream",
        nameRu: "Сырники с рикоттой и карамельным кремом",
        description: "Ricotta peyniriyle hazırlanan syrniki, karamel kreması ve taze meyvelerle",
        descriptionEn: "Syrniki made with ricotta cheese, caramel cream and fresh fruits",
        descriptionRu: "Сырники из рикотты, карамельный крем и свежие фрукты",
        price: 350,
        calories: 650,
        allergenNames: ["Gluten içeren tahıllar"],
        image: "/menu-seed-images/items/ricotta-syrniki-with-caramel-cream.jpg",
      },
      {
        name: "İngiliz Kahvaltısı",
        nameEn: "English Breakfast",
        nameRu: "Английский завтрак",
        description: "Klasik İngiliz kahvaltısı: tavuk sosis, dana bacon, yumurta, mantar, patates ve domates soslu fasulye",
        descriptionEn: "Classic English breakfast: chicken sausage, beef bacon, egg, mushroom, potato and beans in tomato sauce",
        descriptionRu: "Классический английский завтрак: куриные колбаски, говяжий бекон, яйцо, грибы, картофель и фасоль в томатном соусе",
        price: 400,
        calories: 980,
        allergenNames: ["Gluten içeren tahıllar", "Yumurta"],
        image: "/menu-seed-images/items/english-breakfast.jpg",
      },
      {
        name: "Kahvaltı Tabağı",
        nameEn: "Breakfast Plate",
        nameRu: "Тарелка для завтрака",
        description: "Salatalık, domates, peynir, siyah zeytin, yeşil zeytin, ekmek, tereyağı, sucuk, 2 yumurta",
        descriptionEn: "Cucumber, tomato, cheese, black & green olives, bread, butter, sucuk, 2 eggs",
        descriptionRu: "Огурец, помидор, сыр, чёрные и зелёные оливки, хлеб, масло, суджук, 2 яйца",
        price: 400,
        calories: 816,
        allergenNames: ["Gluten içeren tahıllar", "Yumurta", "Süt (laktoz dahil)"],
        image: "/menu-seed-images/items/breakfast-plate.jpg",
      },
    ],
  },
  {
    name: "Salatalar",
    nameEn: "Salads",
    nameRu: "Салаты",
    section: "food",
    image: "/menu-seed-images/categories/salads.jpg",
    items: [
      {
        name: "Yunan Salatası",
        nameEn: "Greek Salad",
        nameRu: "Греческий салат",
        description: "Domates, salatalık, dolmalık biber, zeytin, feta peyniri, yunan sosu",
        descriptionEn: "Tomato, cucumber, bell pepper, olives, feta cheese, Greek dressing",
        descriptionRu: "Помидор, огурец, болгарский перец, оливки, сыр фета, греческая заправка",
        price: 0,
        calories: 237,
        allergenNames: ["Süt (laktoz dahil)"],
        image: "/menu-seed-images/items/greek-salad.jpg",
      },
      {
        name: "Tavuklu Sezar Salata",
        nameEn: "Chicken Caesar Salad",
        nameRu: "Салат Цезарь с курицей",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 0,
        calories: 617,
        allergenNames: ["Yumurta", "Süt (laktoz dahil)"],
        image: "/menu-seed-images/items/chicken-caesar-salad.jpg",
      },
      {
        name: "Somonlu ve Taze Patatesli Niçoise Salatası",
        nameEn: "Niçoise Salad with Salmon & New Potatoes",
        nameRu: "Салат Нисуаз с лососем и молодым картофелем",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 0,
        calories: 480,
        allergenNames: ["Yumurta", "Süt (laktoz dahil)", "Balık"],
        image: "/menu-seed-images/items/nicoise-salad-with-salmon-new-potatoes.jpg",
      },
      {
        name: "Kaşık Salata",
        nameEn: "Chopped Salad",
        nameRu: "Мелко нарезанный салат",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 0,
        calories: 159,
        image: "/menu-seed-images/items/chopped-salad.jpg",
      },
    ],
  },
  {
    name: "Ana Yemekler",
    nameEn: "Main Courses",
    nameRu: "Основные блюда",
    section: "food",
    image: "/menu-seed-images/categories/main-courses.jpg",
    items: [
      {
        name: "Izgara Köfte",
        nameEn: "Grilled Meatballs",
        nameRu: "Котлеты на гриле",
        description: "Kuzu-dana kıyma, pirinç, patates kızartması, domates, ızgara biber, sos, yeşillik",
        descriptionEn: "Lamb-beef mince, rice, French fries, tomato, grilled pepper, sauce, herbs",
        descriptionRu: "Фарш из баранины и говядины, рис, картофель фри, помидор, перец гриль, соус, зелень",
        price: 500,
        calories: 650,
        allergenNames: ["Gluten içeren tahıllar"],
        image: "/menu-seed-images/items/grilled-meatballs.jpg",
      },
      {
        name: "Et Fajita",
        nameEn: "Beef Fajita",
        nameRu: "Фахитас из говядины",
        description: "Dana eti, dolmalık biber, fasulye, mısır, yeşillik, pita ekmeği",
        descriptionEn: "Beef, bell pepper, beans, corn, herbs, pita bread",
        descriptionRu: "Говядина, болгарский перец, фасоль, кукуруза, зелень, лепёшка пита",
        price: 600,
        calories: 780,
        allergenNames: ["Gluten içeren tahıllar", "Soya", "Lüpin"],
        image: "/menu-seed-images/items/beef-fajita.jpg",
      },
      {
        name: "Tavuk Fajita",
        nameEn: "Chicken Fajita",
        nameRu: "Фахитас из курицы",
        description: "Tavuk eti, dolmalık biber, fasulye, mısır, yeşillik, pita ekmeği",
        descriptionEn: "Chicken, bell pepper, beans, corn, herbs, pita bread",
        descriptionRu: "Курица, болгарский перец, фасоль, кукуруза, зелень, лепёшка пита",
        price: 400,
        calories: 640,
        allergenNames: ["Gluten içeren tahıllar", "Lüpin"],
        image: "/menu-seed-images/items/chicken-fajita.jpg",
      },
      {
        name: "Sebzeli Izgara Piliç",
        nameEn: "Grilled Chicken with Vegetables",
        nameRu: "Курица гриль с овощами",
        description: "Piliç, baharatlar, kabak, dolmalık biber, brokoli, kültür mantarı, mantar sosu",
        descriptionEn: "Chicken, spices, zucchini, bell pepper, broccoli, mushroom, mushroom sauce",
        descriptionRu: "Курица, специи, кабачок, болгарский перец, брокколи, грибы, грибной соус",
        price: 500,
        calories: 720,
        image: "/menu-seed-images/items/grilled-chicken-with-vegetables.jpg",
      },
      {
        name: "Tavuk Wrap",
        nameEn: "Chicken Wrap",
        nameRu: "Ролл с курицей",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 400,
        calories: 980,
        allergenNames: ["Gluten içeren tahıllar", "Süt (laktoz dahil)", "Soya"],
        image: "/menu-seed-images/items/chicken-wrap.jpg",
      },
      {
        name: "Et Wrap",
        nameEn: "Beef Wrap",
        nameRu: "Ролл с говядиной",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 425,
        calories: 1020,
        allergenNames: ["Gluten içeren tahıllar", "Süt (laktoz dahil)", "Soya"],
        image: "/menu-seed-images/items/beef-wrap.jpg",
      },
      {
        name: "Dana Burger",
        nameEn: "Beef Burger",
        nameRu: "Говяжий бургер",
        description: "Dana Köftesi, Eritilmiş Cheddar Peyniri, Taze Domates, Salatalık Turşusu, Soğan, Iceberg Marul, Burger Sosu",
        descriptionEn: "Beef patty, melted cheddar cheese, fresh tomato, pickle, onion, iceberg lettuce, burger sauce",
        descriptionRu: "Говяжья котлета, расплавленный чеддер, свежий помидор, маринованный огурец, лук, айсберг, соус бургер",
        price: 450,
        calories: 1150,
        allergenNames: ["Gluten içeren tahıllar", "Süt (laktoz dahil)", "Hardal"],
        image: "/menu-seed-images/items/beef-burger.jpg",
      },
      {
        name: "Karışık Pizza",
        nameEn: "Mixed Pizza",
        nameRu: "Пицца ассорти",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 500,
        calories: 515,
        image: "/menu-seed-images/items/mixed-pizza.jpg",
      },
      {
        name: "Karışık Atıştırmalık",
        nameEn: "Mixed Snacks",
        nameRu: "Ассорти закусок",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 350,
        calories: 1400,
        image: "/menu-seed-images/items/mixed-snacks.jpg",
      },
    ],
  },
  {
    name: "Siyah Kahve",
    nameEn: "Black Coffee",
    nameRu: "Чёрный кофе",
    section: "drink",
    image: "/menu-seed-images/categories/black-coffee.jpg",
    items: [
      {
        name: "Espresso",
        nameEn: "Espresso",
        nameRu: "Эспрессо",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 145,
        image: "/menu-seed-images/items/espresso.jpg",
      },
      {
        name: "Duble Espresso",
        nameEn: "Double Espresso",
        nameRu: "Двойной эспрессо",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 165,
        image: "/menu-seed-images/items/double-espresso.jpg",
      },
      {
        name: "Amerikano",
        nameEn: "Americano",
        nameRu: "Американо",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 150,
        image: "/menu-seed-images/items/americano.jpg",
      },
      {
        name: "Türk Kahvesi",
        nameEn: "Turkish Coffee",
        nameRu: "Турецкий кофе",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 125,
        image: "/menu-seed-images/items/turkish-coffee.jpg",
      },
      {
        name: "Duble Türk Kahvesi",
        nameEn: "Double Turkish Coffee",
        nameRu: "Двойной турецкий кофе",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 175,
        image: "/menu-seed-images/items/double-turkish-coffee.jpg",
      },
    ],
  },
  {
    name: "Sütlü Kahve",
    nameEn: "Milk Coffee",
    nameRu: "Кофе с молоком",
    section: "drink",
    image: "/menu-seed-images/categories/milk-coffee.jpg",
    items: [
      {
        name: "Macchiato",
        nameEn: "Macchiato",
        nameRu: "Маккиато",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 150,
        image: "/menu-seed-images/items/macchiato.jpg",
      },
      {
        name: "Flat White",
        nameEn: "Flat White",
        nameRu: "Флэт Уайт",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 170,
        image: "/menu-seed-images/items/flat-white.jpg",
      },
      {
        name: "Cappuccino",
        nameEn: "Cappuccino",
        nameRu: "Капучино",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 170,
        image: "/menu-seed-images/items/cappuccino.jpg",
      },
      {
        name: "Cafe Latte",
        nameEn: "Café Latte",
        nameRu: "Латте",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 170,
        image: "/menu-seed-images/items/cafe-latte.jpg",
      },
      {
        name: "Aromalı Latte",
        nameEn: "Flavored Latte",
        nameRu: "Ароматизированный латте",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 185,
        image: "/menu-seed-images/items/flavored-latte.jpg",
      },
      {
        name: "Çikolatalı Mocha",
        nameEn: "Chocolate Mocha",
        nameRu: "Шоколадный мокка",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 185,
        image: "/menu-seed-images/items/chocolate-mocha.jpg",
      },
      {
        name: "Beyaz Çikolatalı Mocha",
        nameEn: "White Chocolate Mocha",
        nameRu: "Мокка с белым шоколадом",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 185,
        image: "/menu-seed-images/items/white-chocolate-mocha.jpg",
      },
    ],
  },
  {
    name: "Ice Coffee",
    nameEn: "Iced Coffee",
    nameRu: "Айс-кофе",
    section: "drink",
    image: "/menu-seed-images/categories/iced-coffee.jpg",
    items: [
      {
        name: "Ice Latte",
        nameEn: "Iced Latte",
        nameRu: "Айс латте",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 170,
        image: "/menu-seed-images/items/iced-latte.jpg",
      },
      {
        name: "Aromalı Ice Latte",
        nameEn: "Flavored Iced Latte",
        nameRu: "Ароматизированный айс латте",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 185,
        image: "/menu-seed-images/items/flavored-iced-latte.jpg",
      },
      {
        name: "Ice Cappuccino",
        nameEn: "Iced Cappuccino",
        nameRu: "Айс капучино",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 170,
        image: "/menu-seed-images/items/iced-cappuccino.jpg",
      },
      {
        name: "Ice Mocha",
        nameEn: "Iced Mocha",
        nameRu: "Айс мокка",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 185,
        image: "/menu-seed-images/items/iced-mocha.jpg",
      },
      {
        name: "Ice White Mocha",
        nameEn: "Iced White Mocha",
        nameRu: "Айс белая мокка",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 185,
        image: "/menu-seed-images/items/iced-white-mocha.jpg",
      },
      {
        name: "Frappe",
        nameEn: "Frappé",
        nameRu: "Фраппе",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 185,
        image: "/menu-seed-images/items/frappe.jpg",
      },
      {
        name: "Espresso Tonic",
        nameEn: "Espresso Tonic",
        nameRu: "Эспрессо тоник",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 200,
        image: "/menu-seed-images/items/espresso-tonic.jpg",
      },
      {
        name: "Ice Americano",
        nameEn: "Iced Americano",
        nameRu: "Айс американо",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 150,
        image: "/menu-seed-images/items/iced-americano.jpg",
      },
      {
        name: "Ice Bumble Coffee",
        nameEn: "Iced Bumblebee Coffee",
        nameRu: "Айс Бамблби",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 200,
        image: "/menu-seed-images/items/iced-bumblebee-coffee.jpg",
      },
    ],
  },
  {
    name: "Sıcak İçecekler",
    nameEn: "Hot Drinks",
    nameRu: "Горячие напитки",
    section: "drink",
    image: "/menu-seed-images/categories/hot-drinks.jpg",
    items: [
      {
        name: "Çay",
        nameEn: "Tea",
        nameRu: "Чай",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 40,
        image: "/menu-seed-images/items/tea.jpg",
      },
      {
        name: "Büyük Çay",
        nameEn: "Large Tea",
        nameRu: "Большой чай",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 55,
        image: "/menu-seed-images/items/large-tea.jpg",
      },
      {
        name: "Sütlü Çay",
        nameEn: "Tea with Milk",
        nameRu: "Чай с молоком",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 80,
        image: "/menu-seed-images/items/tea-with-milk.jpg",
      },
      {
        name: "Sahlep",
        nameEn: "Salep",
        nameRu: "Салеп",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 170,
        image: "/menu-seed-images/items/salep.jpg",
      },
      {
        name: "Sıcak Çikolata",
        nameEn: "Hot Chocolate",
        nameRu: "Горячий шоколад",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 170,
        image: "/menu-seed-images/items/hot-chocolate.jpg",
      },
      {
        name: "Beyaz Sıcak Çikolata",
        nameEn: "White Hot Chocolate",
        nameRu: "Белый горячий шоколад",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 170,
        image: "/menu-seed-images/items/white-hot-chocolate.jpg",
      },
      {
        name: "Süt",
        nameEn: "Milk",
        nameRu: "Молоко",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 85,
        image: "/menu-seed-images/items/milk.jpg",
      },
      {
        name: "Kış Çayı",
        nameEn: "Winter Tea",
        nameRu: "Зимний чай",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 150,
        image: "/menu-seed-images/items/winter-tea.jpg",
      },
      {
        name: "Yeşil Çay",
        nameEn: "Green Tea",
        nameRu: "Зелёный чай",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 150,
        image: "/menu-seed-images/items/green-tea.jpg",
      },
      {
        name: "Mavi Çiçeği Çayı",
        nameEn: "Blue Flower Tea",
        nameRu: "Чай из синего цветка",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 150,
        image: "/menu-seed-images/items/blue-flower-tea.jpg",
      },
      {
        name: "Papatya Çayı",
        nameEn: "Chamomile Tea",
        nameRu: "Ромашковый чай",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 150,
        image: "/menu-seed-images/items/chamomile-tea.jpg",
      },
      {
        name: "Adaçayı",
        nameEn: "Sage Tea",
        nameRu: "Шалфейный чай",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 150,
        image: "/menu-seed-images/items/sage-tea.jpg",
      },
      {
        name: "Ihlamur",
        nameEn: "Linden Tea",
        nameRu: "Липовый чай",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 150,
        image: "/menu-seed-images/items/linden-tea.jpg",
      },
      {
        name: "Hibiskus Çayı",
        nameEn: "Hibiscus Tea",
        nameRu: "Чай каркаде",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 150,
        image: "/menu-seed-images/items/hibiscus-tea.jpg",
      },
      {
        name: "Relax Çay",
        nameEn: "Relax Tea",
        nameRu: "Чай «Релакс»",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 150,
        image: "/menu-seed-images/items/relax-tea.jpg",
      },
      {
        name: "Yasemin Yeşil Çayı",
        nameEn: "Jasmine Green Tea",
        nameRu: "Зелёный чай с жасмином",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 170,
        image: "/menu-seed-images/items/jasmine-green-tea.jpg",
      },
    ],
  },
  {
    name: "Milkshakes",
    nameEn: "Milkshakes",
    nameRu: "Милкшейки",
    section: "drink",
    image: "/menu-seed-images/categories/milkshakes.jpg",
    items: [
      {
        name: "Vanilya Milkshake",
        nameEn: "Vanilla Milkshake",
        nameRu: "Ванильный милкшейк",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 245,
        image: "/menu-seed-images/items/vanilla-milkshake.jpg",
      },
      {
        name: "Çikolata Milkshake",
        nameEn: "Chocolate Milkshake",
        nameRu: "Шоколадный милкшейк",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 245,
        image: "/menu-seed-images/items/chocolate-milkshake.jpg",
      },
      {
        name: "Karamel Milkshake",
        nameEn: "Caramel Milkshake",
        nameRu: "Карамельный милкшейк",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 245,
        image: "/menu-seed-images/items/caramel-milkshake.jpg",
      },
      {
        name: "Muzlu Milkshake",
        nameEn: "Banana Milkshake",
        nameRu: "Банановый милкшейк",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 245,
        image: "/menu-seed-images/items/banana-milkshake.jpg",
      },
      {
        name: "Passion Meyveli",
        nameEn: "Passion Fruit Milkshake",
        nameRu: "Милкшейк маракуйя",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 260,
        image: "/menu-seed-images/items/passion-fruit-milkshake.jpg",
      },
      {
        name: "Çilekli Milkshake",
        nameEn: "Strawberry Milkshake",
        nameRu: "Клубничный милкшейк",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 245,
        image: "/menu-seed-images/items/strawberry-milkshake.jpg",
      },
    ],
  },
  {
    name: "Sağlıklı İçecekler",
    nameEn: "Healthy Drinks",
    nameRu: "Полезные напитки",
    section: "drink",
    image: "/menu-seed-images/categories/healthy-drinks.jpg",
    items: [
      {
        name: "Portakal Suyu",
        nameEn: "Orange Juice",
        nameRu: "Апельсиновый сок",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 200,
        image: "/menu-seed-images/items/orange-juice.jpg",
      },
      {
        name: "Elma Suyu",
        nameEn: "Apple Juice",
        nameRu: "Яблочный сок",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 200,
        image: "/menu-seed-images/items/apple-juice.jpg",
      },
      {
        name: "Havuç Suyu",
        nameEn: "Carrot Juice",
        nameRu: "Морковный сок",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 200,
        image: "/menu-seed-images/items/carrot-juice.jpg",
      },
    ],
  },
  {
    name: "Soft Drinks",
    nameEn: "Soft Drinks",
    nameRu: "Безалкогольные напитки",
    section: "drink",
    image: "/menu-seed-images/categories/soft-drinks.jpg",
    items: [
      {
        name: "Su",
        nameEn: "Water",
        nameRu: "Вода",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 50,
        image: "/menu-seed-images/items/water.jpg",
      },
      {
        name: "Soda",
        nameEn: "Soda Water",
        nameRu: "Содовая",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 80,
        image: "/menu-seed-images/items/soda-water.jpg",
      },
      {
        name: "Coca-Cola",
        nameEn: "Coca-Cola",
        nameRu: "Кока-Кола",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 115,
        image: "/menu-seed-images/items/coca-cola.jpg",
      },
      {
        name: "Fanta",
        nameEn: "Fanta",
        nameRu: "Фанта",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 115,
        image: "/menu-seed-images/items/fanta.jpg",
      },
      {
        name: "Zero",
        nameEn: "Coca-Cola Zero",
        nameRu: "Кока-Кола Зеро",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 115,
        image: "/menu-seed-images/items/coca-cola-zero.jpg",
      },
      {
        name: "Sprite",
        nameEn: "Sprite",
        nameRu: "Спрайт",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 115,
        image: "/menu-seed-images/items/sprite.jpg",
      },
      {
        name: "Fuse Tea (Şeftali, Mango, Limon, Karpuz)",
        nameEn: "Fuse Tea (Peach, Mango, Lemon, Watermelon)",
        nameRu: "Фьюз Ти (персик, манго, лимон, арбуз)",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 115,
        image: "/menu-seed-images/items/fuse-tea-peach-mango-lemon-watermelon.jpg",
      },
      {
        name: "Schweppes Tonic",
        nameEn: "Schweppes Tonic",
        nameRu: "Тоник Schweppes",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 100,
        image: "/menu-seed-images/items/schweppes-tonic.jpg",
      },
      {
        name: "Redbull",
        nameEn: "Red Bull",
        nameRu: "Ред Булл",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 150,
        image: "/menu-seed-images/items/red-bull.jpg",
      },
    ],
  },
  {
    name: "Ev Yapımı Limonata & Mojito",
    nameEn: "Homemade Lemonade & Mojito",
    nameRu: "Домашний лимонад и мохито",
    section: "drink",
    image: "/menu-seed-images/categories/homemade-lemonade-mojito.jpg",
    items: [
      {
        name: "Klasik Limonata",
        nameEn: "Classic Lemonade",
        nameRu: "Классический лимонад",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 200,
        image: "/menu-seed-images/items/classic-lemonade.jpg",
      },
      {
        name: "Nane Limonata",
        nameEn: "Mint Lemonade",
        nameRu: "Лимонад с мятой",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 215,
        image: "/menu-seed-images/items/mint-lemonade.jpg",
      },
      {
        name: "Çilek Limonata",
        nameEn: "Strawberry Lemonade",
        nameRu: "Клубничный лимонад",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 215,
        image: "/menu-seed-images/items/strawberry-lemonade.jpg",
      },
      {
        name: "Mavi Limonata",
        nameEn: "Blue Lemonade",
        nameRu: "Синий лимонад",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 215,
        image: "/menu-seed-images/items/blue-lemonade.jpg",
      },
      {
        name: "Klasik Mojito",
        nameEn: "Classic Mojito",
        nameRu: "Классический мохито",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 230,
        image: "/menu-seed-images/items/classic-mojito.jpg",
      },
      {
        name: "Çilekli Mojito",
        nameEn: "Strawberry Mojito",
        nameRu: "Клубничный мохито",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 230,
        image: "/menu-seed-images/items/strawberry-mojito.jpg",
      },
      {
        name: "Passion Mojito",
        nameEn: "Passion Fruit Mojito",
        nameRu: "Мохито маракуйя",
        description: "",
        descriptionEn: "",
        descriptionRu: "",
        price: 235,
        image: "/menu-seed-images/items/passion-fruit-mojito.jpg",
      },
    ],
  },
];
